import type { University } from "@/app/_calculator/types";

export const universities: University[] = [
  {
    key: "air",
    otherKeys: [
      "au",
      "a-u",
      "air-university",
      "air-university-islamabad",
      "air-uni",
      "air-islamabad",
      "airuniversity",
      "airuniversityislamabad",
      "au-islamabad",
      "au-university",
      "au-uni",
      "air-edu",
      "air-pk",
      "pakistan-air-force-university",
      "paf-university",
      "paf-air-university",
    ],
    label: "Air University Islamabad (AU)",
    logo: "/logos/air-university-islamabad-air.png",
    location: ["E-9", "Islamabad"],
    type: "Public",
    website: "https://au.edu.pk/",
    mapping: [
      { grade: "A", gradePoints: 4.0 },
      { grade: "A-", gradePoints: 3.67 },
      { grade: "B+", gradePoints: 3.33 },
      { grade: "B", gradePoints: 3.0 },
      { grade: "B-", gradePoints: 2.67 },
      { grade: "C+", gradePoints: 2.33 },
      { grade: "C", gradePoints: 2.0 },
      { grade: "C-", gradePoints: 1.67 },
      { grade: "D", gradePoints: 1.0 },
      { grade: "F", gradePoints: 0.0 },
      { grade: "I", gradePoints: 0.0 },
    ],
  },
  {
    key: "aiou",
    otherKeys: [],
    label: "Allama Iqbal Open University (AIOU)",
    logo: "/logos/allama-iqbal-open-university-aiou.png",
    location: ["H-8", "Islamabad"],
    type: "Public",
    website: "https://aiou.edu.pk/",
    mapping: [],
  },
  {
    key: "bahria",
    otherKeys: [],
    label: "Bahria University",
    logo: "/logos/bahria-university.png",
    location: ["E-8", "Islamabad"],
    type: "Public",
    website: "https://bahria.edu.pk/",
    mapping: [],
  },
  {
    key: "cust",
    otherKeys: [],
    label: "Capital University of Science & Technology (CUST)",
    logo: "/logos/capital-university-of-science-and-technology-cust.png",
    location: ["Zone-V", "Islamabad"],
    type: "Private",
    website: "https://cust.edu.pk/",
    mapping: [
      { grade: "A", gradePoints: 4.0 },
      { grade: "A-", gradePoints: 3.67 },
      { grade: "B+", gradePoints: 3.33 },
      { grade: "B", gradePoints: 3.0 },
      { grade: "B-", gradePoints: 2.67 },
      { grade: "C+", gradePoints: 2.33 },
      { grade: "C", gradePoints: 2.0 },
      { grade: "C-", gradePoints: 1.67 },
      { grade: "D+", gradePoints: 1.33 },
      { grade: "D", gradePoints: 1.0 },
      { grade: "F", gradePoints: 0.0 },
    ],
  },
  {
    key: "comsats",
    otherKeys: [
      "cui",
      "c-u-i",
      "comsats-islamabad",
      "comsats-university",
      "comsats-university-islamabad",
      "commission-on-science-and-technology",
      "commission-science-technology",
      "comsats-uni",
      "cui-islamabad",
      "cui-university",
      "cui-uni",
      "comsatuniversity",
      "comsatuniversityislamabad",
      "comsatsuniversity",
      "comsatsuniversityislamabad",
      "comsats-edu",
      "comsats-pk",
    ],
    label: "COMSATS University Islamabad (CUI)",
    logo: "/logos/comsats-university-islamabad-cui.png",
    location: ["Tarlai Kalan", "Islamabad"],
    type: "Public",
    website: "https://comsats.edu.pk/",
    mapping: [
      { grade: "A", gradePoints: 4.0 },
      { grade: "A-", gradePoints: 3.66 },
      { grade: "B+", gradePoints: 3.33 },
      { grade: "B", gradePoints: 3.0 },
      { grade: "B-", gradePoints: 2.66 },
      { grade: "C+", gradePoints: 2.33 },
      { grade: "C", gradePoints: 2.0 },
      { grade: "C-", gradePoints: 1.66 },
      { grade: "D+", gradePoints: 1.33 },
      { grade: "D", gradePoints: 1.0 },
      { grade: "F", gradePoints: 0.0 },
    ],
  },
  {
    key: "fuuast",
    otherKeys: [],
    label: "Federal Urdu University of Arts, Science and Technology (FUUAST)",
    logo: "/logos/federal-urdu-university-of-arts-science-and-technology-fuuast.png",
    location: ["G-7", "Islamabad"],
    type: "Public",
    website: "https://fuuast.edu.pk/",
    mapping: [],
  },
  {
    key: "fui",
    otherKeys: [],
    label: "Foundation University Islamabad (FUI)",
    logo: "/logos/foundation-university-islamabad-fui.png",
    location: ["DHA Phase I", "Islamabad"],
    type: "Private",
    website: "https://fui.edu.pk/",
    mapping: [],
  },
  {
    key: "ibadat",
    otherKeys: [],
    label: "IBADAT International University Islamabad",
    logo: "/logos/ibadat-international-university-islamabad-iiui.jpg",
    location: ["Sihala", "Islamabad"],
    type: "Private",
    website: "https://iiui.edu.pk/",
    mapping: [],
  },
  {
    key: "ist",
    otherKeys: [],
    label: "Institute of Space Technology (IST)",
    logo: "/logos/institute-of-space-technology-ist.jpeg",
    location: ["DHA Phase II", "Islamabad"],
    type: "Public",
    website: "https://ist.edu.pk/",
    mapping: [],
  },
  {
    key: "iiui",
    otherKeys: [
      "iiu",
      "i-i-u-i",
      "i-i-u",
      "iiui-islamabad",
      "iiu-islamabad",
      "international-islamic-university-islamabad",
      "international-islamic-university",
      "islamic-university-islamabad",
      "islamic-university",
      "intl-islamic-university-islamabad",
      "intl-islamic-university",
      "int-islamic-university-islamabad",
      "int-islamic-university",
      "internationalislamicuniversityislamabad",
      "internationalislamicuniversity",
      "islamicuniversityislamabad",
      "islamicuniversity",
      "iiu-uni",
      "iiui-uni",
      "iiui-university",
      "iiu-university",
    ],
    label: "International Islamic University Islamabad (IIUI)",
    logo: "/logos/international-islamic-university-islamabad-iiui.png",
    location: ["H-10", "Islamabad"],
    type: "Public",
    website: "https://iiu.edu.pk/",
    mapping: [
      { grade: "A", gradePoints: 4.0 },
      { grade: "B+", gradePoints: 3.5 },
      { grade: "B", gradePoints: 3.0 },
      { grade: "C+", gradePoints: 2.5 },
      { grade: "C", gradePoints: 2.0 },
      { grade: "D+", gradePoints: 1.5 },
      { grade: "D", gradePoints: 1.0 },
      { grade: "F", gradePoints: 0.0 },
    ],
  },
  {
    key: "myu",
    otherKeys: [],
    label: "Muslim Youth University (MYU)",
    logo: "/logos/muslim-youth-university-myu.png",
    location: ["Jandain", "Islamabad"],
    type: "Private",
    website: "https://myu.edu.pk/",
    mapping: [],
  },
  {
    key: "fast-nuces",
    otherKeys: [],
    label: "National University of Computer and Emerging Sciences (FAST NUCES)",
    logo: "/logos/national-university-of-computer-and-emerging-sciences-fast-nuces.png",
    location: ["H-11", "Islamabad"],
    type: "Private",
    website: "https://nu.edu.pk/",
    mapping: [],
  },
  {
    key: "ndu",
    otherKeys: [],
    label: "National Defence University (NDU)",
    logo: "/logos/national-defence-university-ndu.png",
    location: ["E-9", "Islamabad"],
    type: "Public",
    website: "https://ndu.edu.pk/",
    mapping: [],
  },
  {
    key: "numl",
    otherKeys: [],
    label: "National University of Modern Languages (NUML)",
    logo: "/logos/national-university-of-modern-languages-numl.jpg",
    location: ["H-9", "Islamabad"],
    type: "Public",
    website: "https://numl.edu.pk/",
    mapping: [],
  },
  {
    key: "nust",
    otherKeys: [
      "n-u-s-t",
      "nust-islamabad",
      "national-university-sciences-technology",
      "national-university-of-sciences-and-technology",
      "national-university-sciences-and-technology",
      "national-university-of-sciences-technology",
      "nust-university",
      "nust-uni",
      "nustuniversity",
      "nustuniversityislamabad",
      "nationaluniversitysciencestechnology",
      "nationaluniversityofsciencesandtechnology",
      "nust-pk",
      "nust-edu",
      "nust-h12",
      "nust-h-12",
    ],
    label: "National University of Sciences & Technology (NUST)",
    logo: "/logos/national-university-of-sciences-and-technology-nust.png",
    location: ["H-12", "Islamabad"],
    type: "Public",
    website: "https://nust.edu.pk/",
    mapping: [
      { grade: "A", gradePoints: 4.0 },
      { grade: "B+", gradePoints: 3.5 },
      { grade: "B", gradePoints: 3.0 },
      { grade: "C+", gradePoints: 2.5 },
      { grade: "C", gradePoints: 2.0 },
      { grade: "D+", gradePoints: 1.5 },
      { grade: "D", gradePoints: 1.0 },
      { grade: "F", gradePoints: 0.0 },
      { grade: "I", gradePoints: 0.0 },
      { grade: "W", gradePoints: 0.0 },
      { grade: "Q", gradePoints: 0.0 },
      { grade: "T", gradePoints: 0.0 },
      { grade: "XF", gradePoints: 0.0 },
    ],
  },
  {
    key: "nsu",
    otherKeys: [],
    label: "National Skills University (NSU)",
    logo: "/logos/national-skills-university-nsu.jpg",
    location: ["H-8", "Islamabad"],
    type: "Public",
    website: "https://nsu.edu.pk/",
    mapping: [],
  },
  {
    key: "nutech",
    otherKeys: [],
    label: "National University of Technology (NUTECH)",
    logo: "/logos/national-university-of-technology-nutech.png",
    location: ["I-12", "Islamabad"],
    type: "Public",
    website: "https://nutech.edu.pk/",
    mapping: [],
  },
  {
    key: "pieas",
    otherKeys: [],
    label: "Pakistan Institute of Engineering and Applied Sciences (PIEAS)",
    logo: "/logos/pakistan-institute-of-engineering-and-applied-sciences-pieas.jpg",
    location: ["Nilore", "Islamabad"],
    type: "Public",
    website: "https://pieas.edu.pk/",
    mapping: [],
  },
  {
    key: "pide",
    otherKeys: [],
    label: "Pakistan Institute of Development Economics (PIDE)",
    logo: "/logos/pakistan-institute-of-development-economics-pide.png",
    location: ["QAU", "Islamabad"],
    type: "Public",
    website: "https://pide.org.pk/",
    mapping: [],
  },
  {
    key: "qau",
    otherKeys: [
      "q-a-u",
      "quaid-azam",
      "quaid-i-azam",
      "quaid-e-azam",
      "quaid-azam-university",
      "quaid-i-azam-university",
      "quaid-e-azam-university",
      "quaid-azam-university-islamabad",
      "quaid-i-azam-university-islamabad",
      "quaid-e-azam-university-islamabad",
      "qau-islamabad",
      "qau-university",
      "qau-uni",
      "quaidazamuniversity",
      "quaidazamuniversityislamabad",
      "quaidiazamuniversity",
      "quaidiazamuniversityislamabad",
    ],
    label: "Quaid-i-Azam University Islamabad (QAU)",
    logo: "/logos/quaid-i-azam-university-islamabad-qau.png",
    location: ["Nurpur Shahan", "Islamabad"],
    type: "Public",
    website: "https://qau.edu.pk/",
    mapping: [
      { grade: "A", gradePoints: 4.0 },
      { grade: "A-", gradePoints: 3.8 },
      { grade: "B+", gradePoints: 3.5 },
      { grade: "B", gradePoints: 3.0 },
      { grade: "B-", gradePoints: 2.8 },
      { grade: "C+", gradePoints: 2.5 },
      { grade: "C", gradePoints: 2.0 },
      { grade: "D", gradePoints: 1.0 },
      { grade: "F", gradePoints: 0.0 },
    ],
  },
  {
    key: "riphah",
    otherKeys: [],
    label: "Riphah International University",
    logo: "/logos/riphah-international-university-riphah.jpg",
    location: ["I-14", "Islamabad"],
    type: "Private",
    website: "https://riphah.edu.pk/",
    mapping: [],
  },
  {
    key: "szabmu",
    otherKeys: [],
    label: "Shaheed Zulfiqar Ali Bhutto Medical University (SZABMU)",
    logo: "/logos/shaheed-zulfiqar-ali-bhutto-medical-university-szabmu.jpeg",
    location: ["G-8", "Islamabad"],
    type: "Public",
    website: "https://szabmu.edu.pk/",
    mapping: [],
  },
  {
    key: "stmu",
    otherKeys: [],
    label: "Shifa Tameer-e-Millat University (STMU)",
    logo: "/logos/shifa-tameer-e-millat-university-stmu.png",
    location: ["H-8/4", "Islamabad"],
    type: "Private",
    website: "https://stmu.edu.pk/",
    mapping: [],
  },
  {
    key: "case",
    otherKeys: [],
    label: "Sir Syed CASE Institute of Technology",
    logo: "/logos/sir-syed-case-institute-of-technology.jpeg",
    location: ["B-17", "Islamabad"],
    type: "Private",
    website: "https://case.edu.pk/",
    mapping: [],
  },
  {
    key: "vu",
    otherKeys: [],
    label: "Virtual University of Pakistan (VU)",
    logo: "/logos/virtual-university-of-pakistan-vu.png",
    location: ["G-5/1", "Islamabad"],
    type: "Public",
    website: "https://vu.edu.pk/",
    mapping: [],
  },
];
