import type { University } from "@/app/_calculator/types";

export const universities: University[] = [
  {
    key: "iiui",
    otherKeys: [
      "iiu",
      "i-i-u-i",
      "i-i-u",
      "iiui-islamabad",
      "iiu-islamabad",
      "international-islamic-university-islamabad",
      "international-islamic-university",
      "islamic-university-islamabad",
      "islamic-university",
      "intl-islamic-university-islamabad",
      "intl-islamic-university",
      "int-islamic-university-islamabad",
      "int-islamic-university",
      "internationalislamicuniversityislamabad",
      "internationalislamicuniversity",
      "islamicuniversityislamabad",
      "islamicuniversity",
      "iiu-uni",
      "iiui-uni",
      "iiui-university",
      "iiu-university",
    ],
    label: "International Islamic University Islamabad (IIUI)",
    mapping: [
      { grade: "A", gradePoints: 4.0 },
      { grade: "B+", gradePoints: 3.5 },
      { grade: "B", gradePoints: 3.0 },
      { grade: "C+", gradePoints: 2.5 },
      { grade: "C", gradePoints: 2.0 },
      { grade: "D+", gradePoints: 1.5 },
      { grade: "D", gradePoints: 1.0 },
      { grade: "F", gradePoints: 0.0 },
    ],
  },
  {
    key: "comsats",
    label: "COMSATS University Islamabad (CUI)",
    mapping: [
      { grade: "A", gradePoints: 4.0 },
      { grade: "A-", gradePoints: 3.66 },
      { grade: "B+", gradePoints: 3.33 },
      { grade: "B", gradePoints: 3.0 },
      { grade: "B-", gradePoints: 2.66 },
      { grade: "C+", gradePoints: 2.33 },
      { grade: "C", gradePoints: 2.0 },
      { grade: "C-", gradePoints: 1.66 },
      { grade: "D+", gradePoints: 1.33 },
      { grade: "D", gradePoints: 1.0 },
      { grade: "F", gradePoints: 0.0 },
    ],
  },
  {
    key: "qau",
    label: "Quaid-i-Azam University Islamabad (QAU)",
    mapping: [
      { grade: "A", gradePoints: 4.0 },
      { grade: "A-", gradePoints: 3.8 },
      { grade: "B+", gradePoints: 3.5 },
      { grade: "B", gradePoints: 3.0 },
      { grade: "B-", gradePoints: 2.8 },
      { grade: "C+", gradePoints: 2.5 },
      { grade: "C", gradePoints: 2.0 },
      { grade: "D", gradePoints: 1.0 },
      { grade: "F", gradePoints: 0.0 },
    ],
  },
  {
    key: "nust",
    label: "National University of Sciences & Technology (NUST)",
    mapping: [
      { grade: "A", gradePoints: 4.0 },
      { grade: "B+", gradePoints: 3.5 },
      { grade: "B", gradePoints: 3.0 },
      { grade: "C+", gradePoints: 2.5 },
      { grade: "C", gradePoints: 2.0 },
      { grade: "D+", gradePoints: 1.5 },
      { grade: "D", gradePoints: 1.0 },
      { grade: "F", gradePoints: 0.0 },
      { grade: "I", gradePoints: 0.0 },
      { grade: "W", gradePoints: 0.0 },
      { grade: "Q", gradePoints: 0.0 },
      { grade: "T", gradePoints: 0.0 },
      { grade: "XF", gradePoints: 0.0 },
    ],
  },
  {
    key: "air",
    label: "National University of Sciences & Technology (NUST)",
    mapping: [
      { grade: "A", gradePoints: 4.0 },
      { grade: "A-", gradePoints: 3.67 },
      { grade: "B+", gradePoints: 3.33 },
      { grade: "B", gradePoints: 3.0 },
      { grade: "B-", gradePoints: 2.67 },
      { grade: "C+", gradePoints: 2.33 },
      { grade: "C", gradePoints: 2.0 },
      { grade: "C-", gradePoints: 1.67 },
      { grade: "D", gradePoints: 1.0 },
      { grade: "F", gradePoints: 0.0 },
      { grade: "I", gradePoints: 0.0 },
    ],
  },
];
