import type { University } from "@/app/_calculator/types";

export const universities: University[] = [
  {
    key: "iiui",
    otherKeys: [
      "iiu",
      "i-i-u-i",
      "i-i-u",
      "iiui-islamabad",
      "iiu-islamabad",
      "international-islamic-university-islamabad",
      "international-islamic-university",
      "islamic-university-islamabad",
      "islamic-university",
      "intl-islamic-university-islamabad",
      "intl-islamic-university",
      "int-islamic-university-islamabad",
      "int-islamic-university",
      "internationalislamicuniversityislamabad",
      "internationalislamicuniversity",
      "islamicuniversityislamabad",
      "islamicuniversity",
      "iiu-uni",
      "iiui-uni",
      "iiui-university",
      "iiu-university",
    ],
    label: "International Islamic University Islamabad (IIUI)",
    logo: "/logos/international-islamic-university-islamabad-iiui.png",
    location: "Islamabad",
    website: "https://www.iiu.edu.pk/",
    mapping: [
      { grade: "A", gradePoints: 4.0 },
      { grade: "B+", gradePoints: 3.5 },
      { grade: "B", gradePoints: 3.0 },
      { grade: "C+", gradePoints: 2.5 },
      { grade: "C", gradePoints: 2.0 },
      { grade: "D+", gradePoints: 1.5 },
      { grade: "D", gradePoints: 1.0 },
      { grade: "F", gradePoints: 0.0 },
    ],
  },
  {
    key: "comsats",
    otherKeys: [
      "cui",
      "c-u-i",
      "comsats-islamabad",
      "comsats-university",
      "comsats-university-islamabad",
      "commission-on-science-and-technology",
      "commission-science-technology",
      "comsats-uni",
      "cui-islamabad",
      "cui-university",
      "cui-uni",
      "comsatuniversity",
      "comsatuniversityislamabad",
      "comsatsuniversity",
      "comsatsuniversityislamabad",
      "comsats-edu",
      "comsats-pk",
    ],
    label: "COMSATS University Islamabad (CUI)",
    logo: "/logos/comsats-university-islamabad-cui.png",
    location: "Islamabad",
    website: "https://www.comsats.edu.pk/",
    mapping: [
      { grade: "A", gradePoints: 4.0 },
      { grade: "A-", gradePoints: 3.66 },
      { grade: "B+", gradePoints: 3.33 },
      { grade: "B", gradePoints: 3.0 },
      { grade: "B-", gradePoints: 2.66 },
      { grade: "C+", gradePoints: 2.33 },
      { grade: "C", gradePoints: 2.0 },
      { grade: "C-", gradePoints: 1.66 },
      { grade: "D+", gradePoints: 1.33 },
      { grade: "D", gradePoints: 1.0 },
      { grade: "F", gradePoints: 0.0 },
    ],
  },
  {
    key: "qau",
    otherKeys: [
      "q-a-u",
      "quaid-azam",
      "quaid-i-azam",
      "quaid-e-azam",
      "quaid-azam-university",
      "quaid-i-azam-university",
      "quaid-e-azam-university",
      "quaid-azam-university-islamabad",
      "quaid-i-azam-university-islamabad",
      "quaid-e-azam-university-islamabad",
      "qau-islamabad",
      "qau-university",
      "qau-uni",
      "quaidazamuniversity",
      "quaidazamuniversityislamabad",
      "quaidiazamuniversity",
      "quaidiazamuniversityislamabad",
    ],
    label: "Quaid-i-Azam University Islamabad (QAU)",
    logo: "/logos/quaid-i-azam-university-islamabad-qau.png",
    location: "Islamabad",
    website: "https://www.qau.edu.pk/",
    mapping: [
      { grade: "A", gradePoints: 4.0 },
      { grade: "A-", gradePoints: 3.8 },
      { grade: "B+", gradePoints: 3.5 },
      { grade: "B", gradePoints: 3.0 },
      { grade: "B-", gradePoints: 2.8 },
      { grade: "C+", gradePoints: 2.5 },
      { grade: "C", gradePoints: 2.0 },
      { grade: "D", gradePoints: 1.0 },
      { grade: "F", gradePoints: 0.0 },
    ],
  },
  {
    key: "nust",
    otherKeys: [
      "n-u-s-t",
      "nust-islamabad",
      "national-university-sciences-technology",
      "national-university-of-sciences-and-technology",
      "national-university-sciences-and-technology",
      "national-university-of-sciences-technology",
      "nust-university",
      "nust-uni",
      "nustuniversity",
      "nustuniversityislamabad",
      "nationaluniversitysciencestechnology",
      "nationaluniversityofsciencesandtechnology",
      "nust-pk",
      "nust-edu",
      "nust-h12",
      "nust-h-12",
    ],
    label: "National University of Sciences & Technology (NUST)",
    logo: "/logos/national-university-of-sciences-and-technology-nust.png",
    location: "Islamabad",
    website: "https://www.nust.edu.pk/",
    mapping: [
      { grade: "A", gradePoints: 4.0 },
      { grade: "B+", gradePoints: 3.5 },
      { grade: "B", gradePoints: 3.0 },
      { grade: "C+", gradePoints: 2.5 },
      { grade: "C", gradePoints: 2.0 },
      { grade: "D+", gradePoints: 1.5 },
      { grade: "D", gradePoints: 1.0 },
      { grade: "F", gradePoints: 0.0 },
      { grade: "I", gradePoints: 0.0 },
      { grade: "W", gradePoints: 0.0 },
      { grade: "Q", gradePoints: 0.0 },
      { grade: "T", gradePoints: 0.0 },
      { grade: "XF", gradePoints: 0.0 },
    ],
  },
  {
    key: "air",
    otherKeys: [
      "au",
      "a-u",
      "air-university",
      "air-university-islamabad",
      "air-uni",
      "air-islamabad",
      "airuniversity",
      "airuniversityislamabad",
      "au-islamabad",
      "au-university",
      "au-uni",
      "air-edu",
      "air-pk",
      "pakistan-air-force-university",
      "paf-university",
      "paf-air-university",
    ],
    label: "Air University Islamabad (AIR)",
    logo: "/logos/air-university-islamabad-air.png",
    location: "Islamabad",
    website: "https://www.au.edu.pk/",
    mapping: [
      { grade: "A", gradePoints: 4.0 },
      { grade: "A-", gradePoints: 3.67 },
      { grade: "B+", gradePoints: 3.33 },
      { grade: "B", gradePoints: 3.0 },
      { grade: "B-", gradePoints: 2.67 },
      { grade: "C+", gradePoints: 2.33 },
      { grade: "C", gradePoints: 2.0 },
      { grade: "C-", gradePoints: 1.67 },
      { grade: "D", gradePoints: 1.0 },
      { grade: "F", gradePoints: 0.0 },
      { grade: "I", gradePoints: 0.0 },
    ],
  },
];
